{"uid":"487870fa1962cb76","name":"launchApp","fullName":"fanfare.dev.FractionCodes2.AutoReportGeneratedClass.launchApp","historyId":"40bc47d429dff80f156f316672e1776a","time":{"start":1723450642497,"stop":1723450642498,"duration":1},"description":"Launching the app","descriptionHtml":"<p>Launching the app</p>\n","status":"skipped","statusMessage":"The local appium server has not been started\nReason: Timed out waiting for [http://127.0.0.1:4723/status] to be available after 20014 ms\nConsider increasing the server startup timeout value (currently 20000ms)\nNode.js executable path: C:\\Program Files\\nodejs\\node.exe\nArguments: [C:\\Users\\TalentPro\\AppData\\Roaming\\npm\\node_modules\\appium\\build\\lib\\main.js, --port, 4723, --address, 127.0.0.1, --log, C:\\Users\\TalentPro\\Desktop\\AppiumServer.txt, --allow-insecure, adb_shell, --log-level, info, --base-path, /, --relaxed-security, --session-override]\nOutput: Tried to attach logging to file 'C:\\Users\\TalentPro\\Desktop\\AppiumServer.txt' but an error occurred: EBUSY: resource busy or locked, unlink 'C:\\Users\\TalentPro\\Desktop\\AppiumServer.txt'\n\u001B[35m[Appium]\u001B[39m Welcome to Appium v2.9.0\r\n\u001B[35m[Appium]\u001B[39m Non-default server args:\r\n\u001B[35m[Appium]\u001B[39m { address: \u001B[32m'127.0.0.1'\u001B[39m,\r\n\u001B[35m[Appium]\u001B[39m   allowInsecure: [ \u001B[32m'adb_shell'\u001B[39m ],\r\n\u001B[35m[Appium]\u001B[39m   basePath: \u001B[32m'/'\u001B[39m,\r\n\u001B[35m[Appium]\u001B[39m   loglevel: \u001B[32m'info'\u001B[39m,\r\n\u001B[35m[Appium]\u001B[39m   relaxedSecurityEnabled: \u001B[33mtrue\u001B[39m,\r\n\u001B[35m[Appium]\u001B[39m   sessionOverride: \u001B[33mtrue\u001B[39m }\r\n\u001B[35m[Appium]\u001B[39m Attempting to load driver flutter...\r\n\u001B[35m[Appium]\u001B[39m Attempting to load driver uiautomator2...\r\n\u001B[38;5;0m[HTTP]\u001B[0m Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other instance of this server running already.\r\n\u001B[35m[Appium]\u001B[39m Could not configure Appium server. It's possible that a driver or plugin tried to update the server and failed. Original error: listen EADDRINUSE: address already in use 127.0.0.1:4723\r\n","statusTrace":"io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: The local appium server has not been started\nReason: Timed out waiting for [http://127.0.0.1:4723/status] to be available after 20014 ms\nConsider increasing the server startup timeout value (currently 20000ms)\nNode.js executable path: C:\\Program Files\\nodejs\\node.exe\nArguments: [C:\\Users\\TalentPro\\AppData\\Roaming\\npm\\node_modules\\appium\\build\\lib\\main.js, --port, 4723, --address, 127.0.0.1, --log, C:\\Users\\TalentPro\\Desktop\\AppiumServer.txt, --allow-insecure, adb_shell, --log-level, info, --base-path, /, --relaxed-security, --session-override]\nOutput: Tried to attach logging to file 'C:\\Users\\TalentPro\\Desktop\\AppiumServer.txt' but an error occurred: EBUSY: resource busy or locked, unlink 'C:\\Users\\TalentPro\\Desktop\\AppiumServer.txt'\n\u001B[35m[Appium]\u001B[39m Welcome to Appium v2.9.0\r\n\u001B[35m[Appium]\u001B[39m Non-default server args:\r\n\u001B[35m[Appium]\u001B[39m { address: \u001B[32m'127.0.0.1'\u001B[39m,\r\n\u001B[35m[Appium]\u001B[39m   allowInsecure: [ \u001B[32m'adb_shell'\u001B[39m ],\r\n\u001B[35m[Appium]\u001B[39m   basePath: \u001B[32m'/'\u001B[39m,\r\n\u001B[35m[Appium]\u001B[39m   loglevel: \u001B[32m'info'\u001B[39m,\r\n\u001B[35m[Appium]\u001B[39m   relaxedSecurityEnabled: \u001B[33mtrue\u001B[39m,\r\n\u001B[35m[Appium]\u001B[39m   sessionOverride: \u001B[33mtrue\u001B[39m }\r\n\u001B[35m[Appium]\u001B[39m Attempting to load driver flutter...\r\n\u001B[35m[Appium]\u001B[39m Attempting to load driver uiautomator2...\r\n\u001B[38;5;0m[HTTP]\u001B[0m Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other instance of this server running already.\r\n\u001B[35m[Appium]\u001B[39m Could not configure Appium server. It's possible that a driver or plugin tried to update the server and failed. Original error: listen EADDRINUSE: address already in use 127.0.0.1:4723\r\n\r\n\tat io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:201)\r\n\tat fanfare.dev.FractionCodes2.AutoReportGeneratedClass.startAppiumServer(AutoReportGeneratedClass.java:56)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\r\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)\r\n\tat org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)\r\n\tat org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)\r\n\tat org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:661)\r\n\tat org.testng.TestRunner.beforeRun(TestRunner.java:650)\r\n\tat org.testng.TestRunner.run(TestRunner.java:612)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:443)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:336)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1228)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1134)\r\n\tat org.testng.TestNG.run(TestNG.java:1101)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\r\nCaused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://127.0.0.1:4723/status] to be available after 20014 ms\r\n\tat org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:94)\r\n\tat io.appium.java_client.service.local.AppiumDriverLocalService.ping(AppiumDriverLocalService.java:157)\r\n\tat io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:180)\r\n\t... 24 more\r\nCaused by: java.util.concurrent.TimeoutException\r\n\tat java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)\r\n\tat org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:91)\r\n\t... 26 more\r\n","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"startAppiumServer","time":{"start":1723450622189,"stop":1723450642288,"duration":20099},"description":"Starting the Appium server and setting up capabilities","status":"broken","statusMessage":"The local appium server has not been started\nReason: Timed out waiting for [http://127.0.0.1:4723/status] to be available after 20014 ms\nConsider increasing the server startup timeout value (currently 20000ms)\nNode.js executable path: C:\\Program Files\\nodejs\\node.exe\nArguments: [C:\\Users\\TalentPro\\AppData\\Roaming\\npm\\node_modules\\appium\\build\\lib\\main.js, --port, 4723, --address, 127.0.0.1, --log, C:\\Users\\TalentPro\\Desktop\\AppiumServer.txt, --allow-insecure, adb_shell, --log-level, info, --base-path, /, --relaxed-security, --session-override]\nOutput: Tried to attach logging to file 'C:\\Users\\TalentPro\\Desktop\\AppiumServer.txt' but an error occurred: EBUSY: resource busy or locked, unlink 'C:\\Users\\TalentPro\\Desktop\\AppiumServer.txt'\n\u001B[35m[Appium]\u001B[39m Welcome to Appium v2.9.0\r\n\u001B[35m[Appium]\u001B[39m Non-default server args:\r\n\u001B[35m[Appium]\u001B[39m { address: \u001B[32m'127.0.0.1'\u001B[39m,\r\n\u001B[35m[Appium]\u001B[39m   allowInsecure: [ \u001B[32m'adb_shell'\u001B[39m ],\r\n\u001B[35m[Appium]\u001B[39m   basePath: \u001B[32m'/'\u001B[39m,\r\n\u001B[35m[Appium]\u001B[39m   loglevel: \u001B[32m'info'\u001B[39m,\r\n\u001B[35m[Appium]\u001B[39m   relaxedSecurityEnabled: \u001B[33mtrue\u001B[39m,\r\n\u001B[35m[Appium]\u001B[39m   sessionOverride: \u001B[33mtrue\u001B[39m }\r\n\u001B[35m[Appium]\u001B[39m Attempting to load driver flutter...\r\n\u001B[35m[Appium]\u001B[39m Attempting to load driver uiautomator2...\r\n\u001B[38;5;0m[HTTP]\u001B[0m Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other instance of this server running already.\r\n\u001B[35m[Appium]\u001B[39m Could not configure Appium server. It's possible that a driver or plugin tried to update the server and failed. Original error: listen EADDRINUSE: address already in use 127.0.0.1:4723\r\n","statusTrace":"io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: The local appium server has not been started\nReason: Timed out waiting for [http://127.0.0.1:4723/status] to be available after 20014 ms\nConsider increasing the server startup timeout value (currently 20000ms)\nNode.js executable path: C:\\Program Files\\nodejs\\node.exe\nArguments: [C:\\Users\\TalentPro\\AppData\\Roaming\\npm\\node_modules\\appium\\build\\lib\\main.js, --port, 4723, --address, 127.0.0.1, --log, C:\\Users\\TalentPro\\Desktop\\AppiumServer.txt, --allow-insecure, adb_shell, --log-level, info, --base-path, /, --relaxed-security, --session-override]\nOutput: Tried to attach logging to file 'C:\\Users\\TalentPro\\Desktop\\AppiumServer.txt' but an error occurred: EBUSY: resource busy or locked, unlink 'C:\\Users\\TalentPro\\Desktop\\AppiumServer.txt'\n\u001B[35m[Appium]\u001B[39m Welcome to Appium v2.9.0\r\n\u001B[35m[Appium]\u001B[39m Non-default server args:\r\n\u001B[35m[Appium]\u001B[39m { address: \u001B[32m'127.0.0.1'\u001B[39m,\r\n\u001B[35m[Appium]\u001B[39m   allowInsecure: [ \u001B[32m'adb_shell'\u001B[39m ],\r\n\u001B[35m[Appium]\u001B[39m   basePath: \u001B[32m'/'\u001B[39m,\r\n\u001B[35m[Appium]\u001B[39m   loglevel: \u001B[32m'info'\u001B[39m,\r\n\u001B[35m[Appium]\u001B[39m   relaxedSecurityEnabled: \u001B[33mtrue\u001B[39m,\r\n\u001B[35m[Appium]\u001B[39m   sessionOverride: \u001B[33mtrue\u001B[39m }\r\n\u001B[35m[Appium]\u001B[39m Attempting to load driver flutter...\r\n\u001B[35m[Appium]\u001B[39m Attempting to load driver uiautomator2...\r\n\u001B[38;5;0m[HTTP]\u001B[0m Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other instance of this server running already.\r\n\u001B[35m[Appium]\u001B[39m Could not configure Appium server. It's possible that a driver or plugin tried to update the server and failed. Original error: listen EADDRINUSE: address already in use 127.0.0.1:4723\r\n\r\n\tat io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:201)\r\n\tat fanfare.dev.FractionCodes2.AutoReportGeneratedClass.startAppiumServer(AutoReportGeneratedClass.java:56)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\r\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)\r\n\tat org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)\r\n\tat org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)\r\n\tat org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:661)\r\n\tat org.testng.TestRunner.beforeRun(TestRunner.java:650)\r\n\tat org.testng.TestRunner.run(TestRunner.java:612)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:443)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:336)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1228)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1134)\r\n\tat org.testng.TestNG.run(TestNG.java:1101)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\r\nCaused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://127.0.0.1:4723/status] to be available after 20014 ms\r\n\tat org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:94)\r\n\tat io.appium.java_client.service.local.AppiumDriverLocalService.ping(AppiumDriverLocalService.java:157)\r\n\tat io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:180)\r\n\t... 24 more\r\nCaused by: java.util.concurrent.TimeoutException\r\n\tat java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)\r\n\tat org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:91)\r\n\t... 26 more\r\n","steps":[],"attachments":[],"parameters":[],"attachmentsCount":0,"shouldDisplayMessage":true,"stepsCount":0,"attachmentStep":false,"hasContent":true}],"afterStages":[{"name":"tearDown","time":{"start":1723450642517,"stop":1723450642517,"duration":0},"description":"","status":"broken","steps":[],"attachments":[],"parameters":[],"attachmentsCount":0,"shouldDisplayMessage":false,"stepsCount":0,"attachmentStep":false,"hasContent":false}],"labels":[{"name":"package","value":"fanfare.dev.FractionCodes2.AutoReportGeneratedClass"},{"name":"testClass","value":"fanfare.dev.FractionCodes2.AutoReportGeneratedClass"},{"name":"testMethod","value":"launchApp"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"fanfare-allure-reporter"},{"name":"subSuite","value":"fanfare.dev.FractionCodes2.AutoReportGeneratedClass"},{"name":"host","value":"DESKTOP-DO44MD4"},{"name":"thread","value":"2280@DESKTOP-DO44MD4.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":true,"retry":true,"extra":{"categories":[],"tags":[]},"source":"487870fa1962cb76.json","parameterValues":[]}